spring:
  application:
    name: ProviderDemo
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none
server:
  port: 8080
  servlet:
    context-path: /provider
dubbo:
  application:
    name: ProviderDemo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://xxx.xxx.xxx.xxx:28848
