spring:
  application:
    name: ConsumerDemo
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session ????????
  session:
    timeout: 86400
    store-type: none
server:
  port: 8081
  servlet:
    context-path: /consumer
dubbo:
  application:
    name: ConsumerDemo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://xxx.xxx.xxx.xxx:28848