server:
  port: 8080
  servlet:
    context-path: /rabbitmq
spring:
  application:
    name: RabbitMQDemo
  rabbitmq:
    # 单机RabbitMQ
    #host: xxx.xxx.xxx.xxx
    #port: 25672
    # 集群RabbitMQ
    addresses: xxx.xxx.xxx.xxx:25672,xxx.xxx.xxx.xxx:25673,xxx.xxx.xxx.xxx:25674
    virtual-host: /
    username: admin
    password: admin123456
    # 消息确认（ACK）
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
